project_name: auth0-gw

env:
  - REGISTRY=ghcr.io
  - ORG=aserto-dev
  - REPO=auth0-gw

before:
  hooks:

builds:
  -
    id: build
    main: ./cmd/{{.ProjectName}}
    binary: "{{.ProjectName}}"
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s
      - -w
      - -X github.com/{{.Env.ORG}}/{{.Env.REPO}}/pkg/version.ver={{.Version}}
      - -X github.com/{{.Env.ORG}}/{{.Env.REPO}}/pkg/version.commit={{.ShortCommit}}
      - -X github.com/{{.Env.ORG}}/{{.Env.REPO}}/pkg/version.date={{.Date}}
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - format: zip
    rlcp: true
    files:
      - LICENSE.md
      - README.md
    name_template: >-
      {{.ProjectName}}{{ .Version }}_{{ .Os }}_{{- if eq .Arch "amd64" }}x86_64{{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  disable: true
