---
gateway:
  port: 8080
  path: /events

directory:
  host: directory.prod.aserto.com:8443
  api_key: <read-write directory service API key>
  tenant_id: <tenant-id uuid>
  insecure: false

auth0:
  domain: <auth0 domain name>
  client_id: <auth0 client id>
  client_secret: <auth0 client secret>

loader:
  bin_path: /app
  template: /app/tmpl/transform.tmpl

scheduler:
  interval: 15m
