---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:
  ORG: github.com/aserto-dev
  REPO: auth0-gw
  BIN: auth0-gw

tasks:
  build:
    cmds:
      - .ext/gobin/goreleaser build --clean --single-target --snapshot
    preconditions:
      - test -f .ext/gobin/goreleaser

  build-all:
    cmds:
      - .ext/gobin/goreleaser build --clean --snapshot
    preconditions:
      - test -f .ext/gobin/goreleaser

  release:
    cmds:
      - .ext/gobin/goreleaser release --clean --snapshot
    preconditions:
      - test -f .ext/gobin/goreleaser

  lint:
    cmds:
      - .ext/gobin/golangci-lint run
    preconditions:
      - test -f .ext/gobin/golangci-lint

  test:
    cmds:
      - .ext/gobin/gotestsum --format short-verbose -- -count=1 -v ./...
    preconditions:
      - test -f .ext/gobin/gotestsum

  run:
    cmds:
      - ./dist/{{.BIN}}_{{OS}}_{{ARCH}}/{{.BIN}} {{.CLI_ARGS}}

  clean:
    cmds:
      - rm -rf ./dist
      - rm -rf ./.ext
      - rm -rf ./bin

  deps:
    cmds:
      - task: install-goreleaser
      - task: install-golangci-lint
      - task: install-gotestsum

  install-goreleaser:
    internal: true
    cmds:
      - task: go-install
        vars:
          PACKAGE: github.com/goreleaser/goreleaser/v2
          VERSION: v2.3.2

  install-golangci-lint:
    internal: true
    cmds:
      - task: go-install
        vars:
          PACKAGE: github.com/golangci/golangci-lint/cmd/golangci-lint
          VERSION: v1.61.0

  install-gotestsum:
    internal: true
    cmds:
      - task: go-install
        vars:
          PACKAGE: gotest.tools/gotestsum
          VERSION: v1.11.0

  go-install:
    internal: true
    env:
      GOBIN: "{{.ROOT_DIR}}/.ext/gobin"
    cmds:
      - go install {{.PACKAGE}}@{{.VERSION}}
